/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libcifrado_JavaCifrado */

#ifndef _Included_libcifrado_JavaCifrado
#define _Included_libcifrado_JavaCifrado
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libcifrado_JavaCifrado
 * Method:    cifrar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libcifrado_JavaCifrado_cifrar
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     libcifrado_JavaCifrado
 * Method:    descifrar
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_libcifrado_JavaCifrado_descifrar
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
